persistence:
  enabled: true
  type: pvc
  size: 5Gi
  storageClassName: longhorn

admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password

service:
  type: ClusterIP

ingress:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    prune: true
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
        isDefault: true
        editable: true