provider:
  name: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-cloudflare-api-token
        key: api-token
sources:
  - ingress
domainFilters:
  - watworld.uk
policy: sync
registry: txt
txtOwnerId: homelab-k3s